import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <nav>
            <Link className="pb-3 text-zinc-200 col-end-2" href="/">
              Home
            </Link>
            <Link className="pb-3 text-zinc-200" href="/about/founders">
              About
            </Link>
            <Link className="pb-3 text-zinc-200" href="/contact">
              Contact us
            </Link>
            <Link className="pb-3 text-zinc-200" href="/test">
              Test
            </Link>
          </nav>
          <hr className="border-zinc-200" />
        </header>
        {children}
      </body>
    </html>
  );
}
